name: test
on: [push]

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Arch Linux Kernel package
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'pkgbuild'
          pkgname: 'build'
